#!/usr/bin/env python3
"""CLI for Tongji Look (look.tongji.edu.cn): setup, list, transcribe.

This script is designed to be used by a Codex skill:
- Credentials are stored in the skill root `.env` (ignored by `.gitignore`).
- Auth cache is stored in `<skill>/state/`.
- Artifacts are written to `./tongji-output/` under the current working directory.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import getpass
import json
import re
import shutil
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse

from tongji_backend.auth import TongjiAuth
from tongji_backend.client import TongjiClient
from tongji_backend.mineru_parser import resolve_mineru_options, run_mineru_parse
from tongji_backend.slide_pdf import build_slide_pdf, resolve_pdf_options
from tongji_backend.transcriber import NoAudioStreamError, Transcriber, TranscriptionError


def _skill_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _env_path() -> Path:
    return _skill_root() / ".env"


def _state_dir() -> Path:
    return _skill_root() / "state"


def _auth_session_file() -> Path:
    return _state_dir() / "auth_session.json"


def _last_course_file() -> Path:
    return _state_dir() / "last_course.json"


def _output_dir(output_dir: str | None) -> Path:
    return (Path(output_dir).expanduser().resolve() if output_dir else (Path.cwd() / "tongji-output"))


def _slide_pdf_dir() -> Path:
    return (Path.cwd() / "tongji-output" / "slide-pdf").resolve()


def _now_iso() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%S%z")


def _print_err(msg: str) -> None:
    print(f"[ERROR] {msg}", file=sys.stderr)


def _format_hms(total_seconds: int) -> str:
    sec = max(0, int(total_seconds))
    h = sec // 3600
    m = (sec % 3600) // 60
    s = sec % 60
    return f"{h:02d}-{m:02d}-{s:02d}"


def _safe_filename_part(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", value.strip())
    return cleaned.strip("._-") or "item"


def _guess_ext_from_url(url: str) -> str:
    path = urlparse(url).path or ""
    suffix = Path(path).suffix.lower()
    if suffix in {".jpg", ".jpeg", ".png", ".webp", ".bmp"}:
        return suffix
    return ".jpg"


def _trash_dir() -> Path:
    return _skill_root() / ".trash"


def _move_to_trash(path: Path) -> None:
    if not path.exists():
        return
    _trash_dir().mkdir(parents=True, exist_ok=True)
    ts = time.strftime("%Y%m%d-%H%M%S")
    target = _trash_dir() / f"{path.name}.{ts}"
    try:
        path.replace(target)
    except Exception:
        try:
            shutil.move(str(path), str(target))
        except Exception:
            pass


def _parse_env_lines(raw: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if value.startswith('"') and value.endswith('"') and len(value) >= 2:
            value = value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
        result[key] = value
    return result


def _quote_env_value(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f"\"{escaped}\""


def _write_env_file(path: Path, pairs: dict[str, str]) -> None:
    lines = ["# Auto-generated by look-tongji-notes", f"# Updated: {_now_iso()}"]
    for key, value in pairs.items():
        lines.append(f"{key}={_quote_env_value(value)}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


@dataclass(frozen=True)
class AuthSession:
    username: str
    jwt_token: str


def _save_auth_session(session: AuthSession) -> None:
    _state_dir().mkdir(parents=True, exist_ok=True)
    _auth_session_file().write_text(
        json.dumps(
            {"username": session.username, "jwt_token": session.jwt_token, "updated_at": _now_iso()},
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def _load_auth_session() -> AuthSession | None:
    path = _auth_session_file()
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        username = (data.get("username") or "").strip()
        jwt_token = (data.get("jwt_token") or "").strip()
        if not jwt_token:
            return None
        return AuthSession(username=username, jwt_token=jwt_token)
    except Exception:
        return None


def _clear_auth_session() -> None:
    _move_to_trash(_auth_session_file())


def _build_client_from_jwt(jwt_token: str) -> TongjiClient | None:
    auth = TongjiAuth()
    auth.jwt_token = jwt_token
    auth._setup_bearer_auth()
    auth.logged_in = True
    if not auth.check_alive():
        return None
    return TongjiClient(auth)


def _ensure_authenticated_client(force_login: bool = False) -> tuple[TongjiClient, str]:
    # 1) Try cached JWT first
    if not force_login:
        cached = _load_auth_session()
        if cached:
            client = _build_client_from_jwt(cached.jwt_token)
            if client is not None:
                return client, cached.username

    # 2) Login using env vars (loaded by tongji_backend.config)
    try:
        from tongji_backend import config
    except Exception as e:
        raise RuntimeError(f"Failed to import config: {e}") from e

    username = (config.TONGJI_USERNAME or "").strip()
    password = (config.TONGJI_PASSWORD or "").strip()
    if not username or not password:
        raise RuntimeError(
            "Missing credentials. Run `setup` to create .env, "
            "or set TONGJI_USERNAME/TONGJI_PASSWORD in the environment."
        )

    auth = TongjiAuth()
    auth.login(username=username, password=password)
    jwt_token = auth.get_jwt_token() or ""
    if jwt_token:
        _save_auth_session(AuthSession(username=username, jwt_token=jwt_token))
    return TongjiClient(auth), username


def _check_deps() -> list[str]:
    missing: list[str] = []
    if shutil.which("ffmpeg") is None:
        missing.append("ffmpeg")
    for module in ("requests", "dotenv", "playwright.sync_api"):
        try:
            __import__(module)
        except Exception:
            missing.append(module)
    return missing


def cmd_setup(args: argparse.Namespace) -> int:
    missing = _check_deps()
    if missing:
        print("[Setup] Missing dependencies:")
        for item in missing:
            print(f"  - {item}")
        print("\n[Setup] Install Python deps with:")
        print(f"  pip install -r \"{_skill_root() / 'requirements.txt'}\"")
        print("[Setup] Install Playwright browser with:")
        print("  python -m playwright install chromium")
        print()

    env_file = _env_path()
    if env_file.exists() and not args.overwrite:
        _print_err(f".env already exists at {env_file}. Re-run with --overwrite to replace it.")
        return 2

    username = (args.username or "").strip()
    password = (args.password or "").strip()

    if not username:
        username = input("Tongji username (student/staff ID): ").strip()
    if not password:
        password = getpass.getpass("Tongji password (input hidden): ").strip()

    if not username or not password:
        _print_err("Username/password cannot be empty.")
        return 2

    existing: dict[str, str] = {}
    if env_file.exists():
        try:
            existing = _parse_env_lines(env_file.read_text(encoding="utf-8"))
        except Exception:
            existing = {}

    existing["TONGJI_USERNAME"] = username
    existing["TONGJI_PASSWORD"] = password
    _write_env_file(env_file, existing)
    _clear_auth_session()
    print(f"[Setup] Saved credentials to: {env_file}")
    print("[Setup] Done.")
    return 0


def _save_last_course(course: dict[str, Any]) -> None:
    _state_dir().mkdir(parents=True, exist_ok=True)
    _last_course_file().write_text(
        json.dumps({"course": course, "updated_at": _now_iso()}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def _load_last_course_id() -> str | None:
    path = _last_course_file()
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        course = data.get("course") or {}
        course_id = (course.get("course_id") or "").strip()
        return course_id or None
    except Exception:
        return None


def cmd_list(args: argparse.Namespace) -> int:
    try:
        client, username = _ensure_authenticated_client(force_login=args.force_login)
    except Exception as e:
        _print_err(str(e))
        return 1

    query = (args.query or "").strip().lower()

    if args.all_courses:
        courses = client.get_all_courses()
    else:
        courses = client.get_recent_courses(per_page=max(1, int(args.limit)))

    if not courses:
        _print_err("No courses found.")
        return 1

    print(f"[List] Logged in as: {username or '(unknown)'}")

    def _course_title(course: dict[str, Any]) -> str:
        return str(course.get("title") or course.get("course_title") or "").strip()

    def _course_teacher(course: dict[str, Any]) -> str:
        return str(course.get("teacher") or course.get("realname") or "").strip()

    if query:
        courses = [
            c for c in courses
            if query in _course_title(c).lower() or query in _course_teacher(c).lower()
        ]

    if not courses:
        _print_err("No courses matched the query.")
        return 1

    header = "All courses" if args.all_courses else "Recent courses"
    if query:
        header += f" (query: {args.query})"
    print(f"[List] {header}:")

    shown = courses[: max(1, int(args.limit))]
    for idx, c in enumerate(shown, 1):
        title = _course_title(c)
        teacher = _course_teacher(c)
        cid = str(c.get("course_id") or "").strip()
        label = f"{title} ({cid})"
        if teacher:
            label += f" / {teacher}"
        print(f"  {idx}. {label}")

    choose = args.choose
    if choose is None:
        raw = input("\nChoose a course number (or press Enter to skip): ").strip()
        if not raw:
            return 0
        choose = int(raw)

    if choose < 1 or choose > len(shown):
        _print_err(f"Invalid selection: {choose}")
        return 2

    selected = shown[choose - 1]
    _save_last_course(selected)
    print(f"[List] Selected: {_course_title(selected)} ({selected.get('course_id', '')})")
    return 0


def _extract_ids_from_url(url: str) -> tuple[str | None, str | None]:
    parsed = urlparse(url)

    query_parts: list[str] = []
    if parsed.query:
        query_parts.append(parsed.query)
    if parsed.fragment and "?" in parsed.fragment:
        query_parts.append(parsed.fragment.split("?", 1)[1])

    params: dict[str, str] = {}
    for part in query_parts:
        for k, v in parse_qs(part).items():
            if not v:
                continue
            params[k.lower()] = v[0]

    course_id = (
        params.get("course_id")
        or params.get("courseid")
        or params.get("cid")
        or params.get("course")
    )
    sub_id = (
        params.get("sub_id")
        or params.get("subid")
        or params.get("sid")
        or params.get("sub")
    )

    # Best-effort: try to find `sub_id` in fragment path (e.g. "#/play/12345")
    if not sub_id and parsed.fragment:
        m = re.search(r"/play/(\d+)", parsed.fragment)
        if m:
            sub_id = m.group(1)

    return course_id, sub_id


def _choose_lecture_from_course(client: TongjiClient, course_id: str, limit: int) -> tuple[str, dict[str, Any] | None]:
    detail = client.get_course_detail(course_id)
    lectures = detail.get("lectures") or []
    if not isinstance(lectures, list) or not lectures:
        raise RuntimeError("No lectures found for this course.")

    # Prefer playable lectures; keep fallback to show something
    playable = [l for l in lectures if l.get("has_playback") is True]
    candidates = playable or lectures

    def _sort_key(item: dict[str, Any]) -> str:
        return str(item.get("date") or "")

    candidates = sorted(candidates, key=_sort_key, reverse=True)[:limit]

    print("[Select] Lectures (latest first):")
    for idx, lec in enumerate(candidates, 1):
        sub_id = str(lec.get("sub_id") or "")
        title = str(lec.get("sub_title") or "").strip()
        date = str(lec.get("date") or "").strip()
        flag = "playback" if lec.get("has_playback") else "no-playback"
        display = " ".join([p for p in [date, title] if p]).strip()
        print(f"  {idx}. {display} ({sub_id}) [{flag}]")

    raw = input("\nChoose a lecture number: ").strip()
    if not raw:
        raise RuntimeError("No lecture selected.")
    choose = int(raw)
    if choose < 1 or choose > len(candidates):
        raise RuntimeError(f"Invalid lecture selection: {choose}")

    selected = candidates[choose - 1]
    return str(selected.get("sub_id") or ""), selected


def _resolve_course_sub(
    client: TongjiClient,
    *,
    lecture_url: str,
    course_id: str,
    sub_id: str,
    lecture_limit: int,
    tag: str,
) -> tuple[str, str] | None:
    course_id = (course_id or "").strip()
    sub_id = (sub_id or "").strip()

    if lecture_url:
        parsed_course_id, parsed_sub_id = _extract_ids_from_url(lecture_url)
        course_id = course_id or (parsed_course_id or "")
        sub_id = sub_id or (parsed_sub_id or "")

    if not course_id:
        last = _load_last_course_id()
        if last:
            print(f"[{tag}] Using last selected course_id from state: {last}")
            course_id = last

    if not course_id:
        _print_err("Missing course_id. Provide --course-id or --lecture-url that contains it.")
        return None

    if not sub_id:
        try:
            sub_id, _ = _choose_lecture_from_course(client, course_id, limit=lecture_limit)
        except Exception as e:
            _print_err(str(e))
            return None
    return course_id, sub_id


def _run_transcript_job(
    *,
    client: TongjiClient,
    username: str,
    course_id: str,
    sub_id: str,
    lecture_url: str,
    output_dir: str,
    tag: str = "Transcript",
) -> int:
    print(f"[{tag}] Logged in as: {username or '(unknown)'}")
    print(f"[{tag}] course_id={course_id} sub_id={sub_id}")
    video_url = client.get_video_url(course_id, sub_id)
    if not video_url:
        _print_err("Failed to resolve video URL. The lecture may not have playback enabled.")
        return 1

    stream_url, http_headers = client.get_stream_params(video_url)
    transcriber = Transcriber()

    try:
        transcript, srt_content, utterances = transcriber.transcribe_url(
            stream_url, http_headers=http_headers
        )
    except NoAudioStreamError as e:
        _print_err(f"No audio stream: {e}")
        return 1
    except TranscriptionError as e:
        _print_err(f"Transcription failed: {e}")
        return 1
    except Exception as e:
        _print_err(f"Unexpected error: {type(e).__name__}: {e}")
        return 1

    out_dir = _output_dir(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    base = f"{course_id}_{sub_id}"
    txt_path = out_dir / f"{base}.txt"
    srt_path = out_dir / f"{base}.srt"
    meta_path = out_dir / f"{base}.json"

    txt_path.write_text(transcript.strip() + "\n", encoding="utf-8")
    if srt_content:
        srt_path.write_text(srt_content.strip() + "\n", encoding="utf-8")
    meta_path.write_text(
        json.dumps(
            {
                "course_id": course_id,
                "sub_id": sub_id,
                "lecture_url": lecture_url or "",
                "video_url": video_url,
                "generated_at": _now_iso(),
                "user": username or "",
                "artifacts": {
                    "transcript_txt": str(txt_path),
                    "subtitle_srt": str(srt_path) if srt_content else "",
                },
                "utterances": utterances or [],
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    print(f"[{tag}] Done. Files written:")
    print(f"  - {txt_path}")
    if srt_content:
        print(f"  - {srt_path}")
    print(f"  - {meta_path}")
    return 0


def _download_one_slide(
    client: TongjiClient,
    item: dict[str, Any],
    out_dir: Path,
    index: int,
    timeout: int,
    retries: int,
) -> tuple[dict[str, Any], str | None]:
    created_sec = int(item.get("created_sec") or 0)
    image_url = str(item.get("image_url") or "").strip()
    if not image_url:
        return item, "missing image_url"

    stamp = _format_hms(created_sec)
    ext = _guess_ext_from_url(image_url)
    filename = f"{index:04d}_t{stamp}_s{created_sec:06d}{ext}"
    path = out_dir / _safe_filename_part(filename)

    last_err = ""
    for attempt in range(1, max(1, retries) + 1):
        try:
            resp = client.session.get(image_url, timeout=timeout)
            if resp.status_code == 200 and resp.content:
                path.write_bytes(resp.content)
                item["filename"] = path.name
                item["filepath"] = str(path)
                item["downloaded_at"] = _now_iso()
                item["bytes"] = len(resp.content)
                return item, None

            last_err = f"http {resp.status_code}"
            if resp.status_code in (429, 500, 502, 503, 504):
                time.sleep(0.5 * attempt)
        except Exception as e:
            last_err = f"{type(e).__name__}: {e}"
            time.sleep(0.5 * attempt)

    return item, last_err or "download failed"


def _run_slide_job(
    *,
    client: TongjiClient,
    username: str,
    course_id: str,
    sub_id: str,
    lecture_url: str,
    output_dir: str,
    per_page: int,
    max_pages: int,
    max_items: int,
    concurrency: int,
    retries: int,
    timeout: int,
    to_pdf: bool,
    scan_mode: str,
    mineru_enabled: bool,
    mineru_pages: str,
    mineru_source: str,
    mineru_lang: str,
    mineru_backend: str,
    mineru_method: str,
    tag: str = "Slide",
) -> int:
    print(f"[{tag}] Logged in as: {username or '(unknown)'}")
    print(f"[{tag}] course_id={course_id} sub_id={sub_id}")
    try:
        snapshots = client.get_ppt_snapshots(
            course_id,
            sub_id,
            per_page=max(1, int(per_page)),
            max_pages=max(1, int(max_pages)),
        )
    except Exception as e:
        _print_err(f"Failed to list slide snapshots: {e}")
        return 1

    if not snapshots:
        _print_err("No slide snapshots found for this lecture.")
        return 1

    if max_items and max_items > 0:
        snapshots = snapshots[: max_items]

    out_dir = (
        Path(output_dir).expanduser().resolve()
        if output_dir
        else (Path.cwd() / "tongji-output" / f"slide_{course_id}_{sub_id}").resolve()
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    concurrency = max(1, min(int(concurrency), 16))
    retries = max(1, min(int(retries), 8))
    timeout = max(5, int(timeout))

    print(
        f"[{tag}] Found {len(snapshots)} snapshots. Downloading with "
        f"concurrency={concurrency}, retries={retries}, timeout={timeout}s ..."
    )

    results: list[dict[str, Any]] = []
    failures: list[dict[str, Any]] = []

    with concurrent.futures.ThreadPoolExecutor(max_workers=concurrency) as executor:
        fut_map = {
            executor.submit(
                _download_one_slide,
                client,
                item,
                out_dir,
                idx,
                timeout,
                retries,
            ): item
            for idx, item in enumerate(snapshots, 1)
        }

        done_count = 0
        total = len(fut_map)
        for fut in concurrent.futures.as_completed(fut_map):
            item, err = fut.result()
            done_count += 1
            if err:
                failures.append({"item": item, "error": err})
            else:
                results.append(item)
            if done_count % 10 == 0 or done_count == total:
                print(f"[{tag}] Progress: {done_count}/{total}")

    results.sort(key=lambda x: int(x.get("created_sec") or 0))

    exported_pdf = ""
    pdf_pages = 0
    pdf_error = ""
    pdf_out_dir = _slide_pdf_dir()
    mineru_result: dict[str, Any] = {
        "enabled": bool(mineru_enabled),
        "ok": False,
        "pages": (mineru_pages or "").strip(),
        "source": (mineru_source or "").strip().lower(),
        "lang": (mineru_lang or "").strip().lower(),
        "backend": (mineru_backend or "").strip().lower(),
        "method": (mineru_method or "").strip().lower(),
        "output_dir": "",
        "md": "",
        "content_list_json": "",
        "content_list_v2_json": "",
        "layout_pdf": "",
        "span_pdf": "",
        "images_dir": "",
        "error": "",
    }

    if mineru_enabled and not to_pdf:
        mineru_result["error"] = "MinerU requires PDF input. Re-run with --to-pdf."
        _print_err(str(mineru_result["error"]))

    if to_pdf:
        image_paths: list[Path] = []
        for item in results:
            raw = str(item.get("filepath") or "").strip()
            if raw:
                image_paths.append(Path(raw))
        pdf_out_dir.mkdir(parents=True, exist_ok=True)
        pdf_path = pdf_out_dir / f"slide_{course_id}_{sub_id}.pdf"
        try:
            pdf_pages, exported = build_slide_pdf(
                image_paths=image_paths,
                pdf_path=pdf_path,
                scan_mode=scan_mode,
            )
            exported_pdf = str(exported)
        except Exception as e:
            pdf_error = f"{type(e).__name__}: {e}"
            _print_err(f"Failed to export PDF: {pdf_error}")

    if mineru_enabled and to_pdf and exported_pdf and not pdf_error:
        try:
            options = resolve_mineru_options(
                enabled=True,
                pages=mineru_pages,
                source=mineru_source,
                lang=mineru_lang,
                backend=mineru_backend,
                method=mineru_method,
            )
            mineru_out = pdf_out_dir / f"mineru_{course_id}_{sub_id}"
            mineru_result = run_mineru_parse(
                pdf_path=Path(exported_pdf),
                output_dir=mineru_out,
                options=options,
            )
            if not mineru_result.get("ok"):
                _print_err(f"MinerU parse failed: {mineru_result.get('error')}")
        except Exception as e:
            mineru_result = {
                "enabled": True,
                "ok": False,
                "pages": (mineru_pages or "").strip(),
                "source": (mineru_source or "").strip().lower(),
                "lang": (mineru_lang or "").strip().lower(),
                "backend": (mineru_backend or "").strip().lower(),
                "method": (mineru_method or "").strip().lower(),
                "output_dir": "",
                "md": "",
                "content_list_json": "",
                "content_list_v2_json": "",
                "layout_pdf": "",
                "span_pdf": "",
                "images_dir": "",
                "error": f"{type(e).__name__}: {e}",
            }
            _print_err(f"MinerU parse failed: {mineru_result['error']}")

    meta_path = out_dir / "index.json"
    meta = {
        "course_id": course_id,
        "sub_id": sub_id,
        "lecture_url": lecture_url or "",
        "generated_at": _now_iso(),
        "user": username or "",
        "download": {
            "requested": len(snapshots),
            "succeeded": len(results),
            "failed": len(failures),
            "concurrency": concurrency,
            "retries": retries,
            "timeout_seconds": timeout,
        },
        "artifacts": {
            "index_json": str(meta_path),
            "pdf": exported_pdf,
            "pdf_pages": pdf_pages,
            "pdf_dir": str(pdf_out_dir) if to_pdf else "",
            "scan_mode": scan_mode if to_pdf else "none",
            "mineru": mineru_result,
        },
        "items": results,
        "failures": failures,
    }
    if pdf_error:
        meta["artifacts"]["pdf_error"] = pdf_error

    meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"[{tag}] Done.")
    print(f"  - output_dir: {out_dir}")
    print(f"  - success: {len(results)}")
    print(f"  - failed: {len(failures)}")
    print(f"  - index: {meta_path}")
    if exported_pdf:
        print(f"  - pdf: {exported_pdf} ({pdf_pages} pages, scan_mode={scan_mode})")
    if mineru_enabled:
        print(f"  - mineru_ok: {bool(mineru_result.get('ok'))}")
        if mineru_result.get("output_dir"):
            print(f"  - mineru_output: {mineru_result.get('output_dir')}")
        if mineru_result.get("error"):
            print(f"  - mineru_error: {mineru_result.get('error')}")
    if failures:
        print(f"[{tag}] Some downloads failed. You can re-run with lower --concurrency (e.g. 2) or higher --retries.")
    if to_pdf and pdf_error:
        return 4
    if mineru_enabled and not bool(mineru_result.get("ok")):
        return 5
    if failures:
        return 3
    return 0


def cmd_transcript(args: argparse.Namespace) -> int:
    try:
        client, username = _ensure_authenticated_client(force_login=args.force_login)
    except Exception as e:
        _print_err(str(e))
        return 1
    resolved = _resolve_course_sub(
        client,
        lecture_url=args.lecture_url,
        course_id=args.course_id,
        sub_id=args.sub_id,
        lecture_limit=args.lecture_limit,
        tag="Transcript",
    )
    if not resolved:
        return 2
    course_id, sub_id = resolved
    return _run_transcript_job(
        client=client,
        username=username,
        course_id=course_id,
        sub_id=sub_id,
        lecture_url=args.lecture_url,
        output_dir=args.output_dir,
        tag="Transcript",
    )


def cmd_slide(args: argparse.Namespace) -> int:
    try:
        client, username = _ensure_authenticated_client(force_login=args.force_login)
    except Exception as e:
        _print_err(str(e))
        return 1
    resolved = _resolve_course_sub(
        client,
        lecture_url=args.lecture_url,
        course_id=args.course_id,
        sub_id=args.sub_id,
        lecture_limit=args.lecture_limit,
        tag="Slide",
    )
    if not resolved:
        return 2
    course_id, sub_id = resolved
    to_pdf, scan_mode = resolve_pdf_options(
        to_pdf=args.to_pdf,
        scan_mode=args.scan_mode,
        tag="Slide",
    )
    return _run_slide_job(
        client=client,
        username=username,
        course_id=course_id,
        sub_id=sub_id,
        lecture_url=args.lecture_url,
        output_dir=args.output_dir,
        per_page=args.per_page,
        max_pages=args.max_pages,
        max_items=args.max_items,
        concurrency=args.concurrency,
        retries=args.retries,
        timeout=args.timeout,
        to_pdf=to_pdf,
        scan_mode=scan_mode,
        mineru_enabled=bool(args.mineru),
        mineru_pages=args.mineru_pages,
        mineru_source=args.mineru_source,
        mineru_lang=args.mineru_lang,
        mineru_backend=args.mineru_backend,
        mineru_method=args.mineru_method,
        tag="Slide",
    )


def cmd_note(args: argparse.Namespace) -> int:
    try:
        client, username = _ensure_authenticated_client(force_login=args.force_login)
    except Exception as e:
        _print_err(str(e))
        return 1
    resolved = _resolve_course_sub(
        client,
        lecture_url=args.lecture_url,
        course_id=args.course_id,
        sub_id=args.sub_id,
        lecture_limit=args.lecture_limit,
        tag="Note",
    )
    if not resolved:
        return 2
    course_id, sub_id = resolved
    to_pdf, scan_mode = resolve_pdf_options(
        to_pdf=args.to_pdf,
        scan_mode=args.scan_mode,
        tag="Note",
    )

    jwt_token = client.auth.get_jwt_token() or ""
    t_client = _build_client_from_jwt(jwt_token) if jwt_token else client
    s_client = _build_client_from_jwt(jwt_token) if jwt_token else client
    t_client = t_client or client
    s_client = s_client or client

    print("[Note] Running transcript and slide jobs in parallel...")
    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
        fut_transcript = executor.submit(
            _run_transcript_job,
            client=t_client,
            username=username,
            course_id=course_id,
            sub_id=sub_id,
            lecture_url=args.lecture_url,
            output_dir=args.output_dir,
            tag="Transcript",
        )
        fut_slide = None
        if not args.no_slide:
            fut_slide = executor.submit(
                _run_slide_job,
                client=s_client,
                username=username,
                course_id=course_id,
                sub_id=sub_id,
                lecture_url=args.lecture_url,
                output_dir=args.slide_output_dir,
                per_page=args.per_page,
                max_pages=args.max_pages,
                max_items=args.max_items,
                concurrency=args.concurrency,
                retries=args.retries,
                timeout=args.timeout,
                to_pdf=to_pdf,
                scan_mode=scan_mode,
                mineru_enabled=bool(args.mineru),
                mineru_pages=args.mineru_pages,
                mineru_source=args.mineru_source,
                mineru_lang=args.mineru_lang,
                mineru_backend=args.mineru_backend,
                mineru_method=args.mineru_method,
                tag="Slide",
            )

        transcript_code = int(fut_transcript.result())
        slide_code = int(fut_slide.result()) if fut_slide is not None else 0

    if transcript_code != 0:
        return transcript_code
    if slide_code != 0:
        return slide_code
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="look_tongji.py")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_setup = sub.add_parser("setup", help="Check deps and write <skill>/.env")
    p_setup.add_argument("--username", default="", help="Tongji username (optional)")
    p_setup.add_argument("--password", default="", help="Tongji password (optional; avoid CLI if possible)")
    p_setup.add_argument("--overwrite", action="store_true", help="Overwrite existing .env")
    p_setup.set_defaults(func=cmd_setup)

    p_list = sub.add_parser("list", help="Login and list recent courses")
    p_list.add_argument("--limit", type=int, default=8, help="Number of courses to show")
    p_list.add_argument(
        "--all",
        dest="all_courses",
        action="store_true",
        help="List all courses (slower but more complete)",
    )
    p_list.add_argument(
        "--query",
        default="",
        help="Filter courses by keyword in title/teacher (case-insensitive)",
    )
    p_list.add_argument("--choose", type=int, default=None, help="Auto-select course number (1-based)")
    p_list.add_argument("--force-login", action="store_true", help="Ignore cached JWT and login again")
    p_list.set_defaults(func=cmd_list)

    p_transcript = sub.add_parser("transcribe", aliases=["transcript", "trans"], help="Transcribe one lecture to SRT/TXT")
    p_transcript.add_argument("--lecture-url", default="", help="Tongji lecture page URL (best-effort parsing)")
    p_transcript.add_argument("--course-id", default="", help="Course ID")
    p_transcript.add_argument("--sub-id", default="", help="Lecture sub_id")
    p_transcript.add_argument("--lecture-limit", type=int, default=20, help="Max lectures shown for interactive choice")
    p_transcript.add_argument("--output-dir", default="", help="Output directory (default: ./tongji-output)")
    p_transcript.add_argument("--force-login", action="store_true", help="Ignore cached JWT and login again")
    p_transcript.set_defaults(func=cmd_transcript)

    p_slide = sub.add_parser("slide", help="Download lecture slide snapshots for one lecture")
    p_slide.add_argument("--lecture-url", default="", help="Tongji lecture page URL (best-effort parsing)")
    p_slide.add_argument("--course-id", default="", help="Course ID")
    p_slide.add_argument("--sub-id", default="", help="Lecture sub_id")
    p_slide.add_argument("--lecture-limit", type=int, default=20, help="Max lectures shown for interactive choice")
    p_slide.add_argument(
        "--output-dir",
        default="",
        help="Output directory (default: ./tongji-output/slide_<course_id>_<sub_id>)",
    )
    p_slide.add_argument("--per-page", type=int, default=100, help="search-ppt per_page parameter")
    p_slide.add_argument("--max-pages", type=int, default=20, help="Max pages to request from search-ppt")
    p_slide.add_argument("--max-items", type=int, default=0, help="Download at most N snapshots (0 means all)")
    p_slide.add_argument("--concurrency", type=int, default=4, help="Concurrent download workers (1-16)")
    p_slide.add_argument("--retries", type=int, default=3, help="Retry attempts per image")
    p_slide.add_argument("--timeout", type=int, default=30, help="HTTP timeout seconds per image request")
    p_slide.add_argument("--to-pdf", action="store_true", help="Pack downloaded slide images into one PDF")
    p_slide.add_argument(
        "--scan-mode",
        choices=["none", "doc", "bw"],
        default="none",
        help="Document scan effect used when --to-pdf is enabled",
    )
    p_slide.add_argument("--mineru", action="store_true", help="Run MinerU OpenAPI parse for the exported PDF")
    p_slide.add_argument(
        "--mineru-pages",
        default="",
        help="MinerU page range in natural 1-based format N-M (example: 17-24). Empty means full PDF.",
    )
    p_slide.add_argument(
        "--mineru-source",
        choices=["openapi"],
        default="openapi",
        help="MinerU provider (currently OpenAPI flash)",
    )
    p_slide.add_argument("--mineru-lang", default="ch", help="Language for MinerU OCR")
    p_slide.add_argument("--mineru-backend", default="openapi", help="MinerU backend")
    p_slide.add_argument("--mineru-method", default="flash", help="MinerU OpenAPI method")
    p_slide.add_argument("--force-login", action="store_true", help="Ignore cached JWT and login again")
    p_slide.set_defaults(func=cmd_slide)

    p_note = sub.add_parser("note", help="Run transcript + slide in parallel for one lecture")
    p_note.add_argument("--lecture-url", default="", help="Tongji lecture page URL (best-effort parsing)")
    p_note.add_argument("--course-id", default="", help="Course ID")
    p_note.add_argument("--sub-id", default="", help="Lecture sub_id")
    p_note.add_argument("--lecture-limit", type=int, default=20, help="Max lectures shown for interactive choice")
    p_note.add_argument("--output-dir", default="", help="Transcript output directory (default: ./tongji-output)")
    p_note.add_argument(
        "--slide-output-dir",
        default="",
        help="Slide output directory (default: ./tongji-output/slide_<course_id>_<sub_id>)",
    )
    p_note.add_argument("--no-slide", action="store_true", help="Skip slide download and run transcript only")
    p_note.add_argument("--per-page", type=int, default=100, help="search-ppt per_page parameter")
    p_note.add_argument("--max-pages", type=int, default=20, help="Max pages to request from search-ppt")
    p_note.add_argument("--max-items", type=int, default=0, help="Download at most N slide snapshots (0 means all)")
    p_note.add_argument("--concurrency", type=int, default=4, help="Concurrent slide download workers (1-16)")
    p_note.add_argument("--retries", type=int, default=3, help="Retry attempts per slide image")
    p_note.add_argument("--timeout", type=int, default=30, help="HTTP timeout seconds per slide image request")
    p_note.add_argument("--to-pdf", action="store_true", help="Pack downloaded slide images into one PDF")
    p_note.add_argument(
        "--scan-mode",
        choices=["none", "doc", "bw"],
        default="none",
        help="Document scan effect used when --to-pdf is enabled",
    )
    p_note.add_argument("--mineru", action="store_true", help="Run MinerU OpenAPI parse for the exported PDF")
    p_note.add_argument(
        "--mineru-pages",
        default="",
        help="MinerU page range in natural 1-based format N-M (example: 17-24). Empty means full PDF.",
    )
    p_note.add_argument(
        "--mineru-source",
        choices=["openapi"],
        default="openapi",
        help="MinerU provider (currently OpenAPI flash)",
    )
    p_note.add_argument("--mineru-lang", default="ch", help="Language for MinerU OCR")
    p_note.add_argument("--mineru-backend", default="openapi", help="MinerU backend")
    p_note.add_argument("--mineru-method", default="flash", help="MinerU OpenAPI method")
    p_note.add_argument("--force-login", action="store_true", help="Ignore cached JWT and login again")
    p_note.set_defaults(func=cmd_note)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
